

name: "macOS vagrant kvm qemu libvirt CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month

jobs:

  macos-latest-vagrant:
      name: "vagrant macos-latest macos-latest 10.15.7 rust"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      - name: "check on brew version"
        run: brew --version   #Homebrew 2.5.12   
      - name: "add Rust to your system PATH manually"
        run:   | 
          brew cask install virtualbox
          brew cask install vagrant
          mkdir ~/vms
          touch ~/vms/Vagrantfile
          cat<<EOF | sudo tee -a ~/vms/Vagrantfile
          # -*- mode: ruby -*-
          # vi: set ft=ruby :VM_BOX  = 'ubuntu/xenial64'
          NETWORK = 'forwarded_port'
          GUEST_PORT = 80
          HOST_PORT = 9000Vagrant.configure(2) do |config|
            config.vm.box = VM_BOX
            config.vm.network NETWORK, guest: GUEST_PORT, host: HOST_PORT
            config.vm.provider "virtualbox" do |vb|
              vb.memory = 1024
            end
            config.vm.provision 'shell', inline: <<-SHELL
              echo 'ubuntu:ubuntu' | sudo chpasswd
            SHELL
          end
          EOF
          cat ~/vms/Vagrantfile
          mkdir ~/vms && vagrant up

  macos-latest-qemu:
      name: "qemu macos-latest macos-latest 10.15.7 rust"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      - name: "check on brew version"
        run: brew --version   #Homebrew 2.5.12   
      - name: "add Rust to your system PATH manually"
        run:   | 
          brew install qemu
          #Create the disk image
          #QCOW2 format to create a 20GB image
          qemu-img create -f qcow2 ubuntu-20.04.1-desktop-amd64.qcow2 20G
          #Boot machine with Ubuntu ISO mounted
          # qemu-system-x86_64 \
          #   -machine type=q35,accel=hvf \
          #   -smp 2 \
          #   -hda ubuntu-20.04.1-desktop-amd64.qcow2 \
          #   -cdrom ./ubuntu-20.04.1-desktop-amd64.iso \
          #   -m 4G \
          #   -vga virtio \
          #   -usb \
          #   -device usb-tablet \
          #   -display default,show-cursor=on

  macos-latest-libvirt-qemu:
      name: "libvirt qemu macos-latest macos-latest 10.15.7 rust"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      - name: "check on brew version"
        run: brew --version   #Homebrew 2.5.12   
      - name: "add Rust to your system PATH manually"
        run:   | 
          brew install qemu gcc libvirt
          echo 'security_driver = "none"' >> /usr/local/etc/libvirt/qemu.conf
          echo "dynamic_ownership = 0" >> /usr/local/etc/libvirt/qemu.conf
          echo "remember_owner = 0" >> /usr/local/etc/libvirt/qemu.conf
          brew services start libvirt
          mkdir ~/vms && cd ~/vms
          qemu-img create -f qcow2 ubuntu.qcow2 50g     
      